dist: trusty
language: java
jdk:
  - openjdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE yogogym;'
  - export TZ=Spain/Madrid
script:
  - mvn test -Dspring.profiles.active=mysql-travis -Dtest=org.springframework.yogogym.web.e2e**
